### ISSUE TITLE
Confusion about how to read the reservation vacancy table

### ISSUE THREAD

**Issue by apanagar** [dhimmel/hackjohn#10]
Hi - Sorry for posting my off topic question in the other issue. I've spent a ton of time in the high sierra but never really bothered with the Yosemite system since it always confused me.

I was wondering if you could help me understand how to read the table of vacancies. Mainly I was wondering, are dates other than the 2-week-out date subject to lottery? For instance, if I wanted to submit a reservation for August 13 (1 available) or September 5 (4 available), are these bookable today (Aug 4)?

Apologies if my question is confusing. I'm trying to determine if it's worth it to work on a scraper to bypass the captcha or if it's the chances of getting any sort of permit through this system is low.

![image](https://user-images.githubusercontent.com/180389/89358198-8fc92d80-d677-11ea-9894-ebe248955ade.png)

**Comment by dhimmel** [comment]
Yes it is confusing. Happy to share what I know, which at this point is a couple of years outdated.

The screenshot you post is of the "trailhead quota report". It shows vacancies that occur after the lottery for that start date has been drawn. The lottery is drawn 168 days in advance. That table will not show any dates more than 168 days in the future. This occurs when lottery winners cancel.

> For instance, if I wanted to submit a reservation for August 13 (1 available) or September 5 (4 available), are these bookable today (Aug 4)?

Those vacancies are bookable by calling the reservation office. If they are still available when you call, then you can book over the phone and pay the fee with credit card (I think its perhaps $10).

As far as the walk-ups, my understanding is that those are day-of walk-ups. You go to the Yosemite permit office in person and then are eligible for a walk-up if there are any left for that day. If people don't show up for their permits, those also become available walk-up.

Does that clear things up?

**Comment by apanagar** [comment]
Ah Thanks! That makes a lot more sense, thanks for clearing that up, I hadn't realize you could call in for bookings!
