### ISSUE TITLE
Running hackjohn from cron

### ISSUE THREAD

**Issue by ndfriedman** [dhimmel/hackjohn#3]
Hi there--very cool project.  I can run hackjohn from the shell, but not from cron--when it runs from cron it does not seem to be able to successfully load the anaconda environment.  Do you mind sharing more details on how you managed to configure it with cron?
I have created a shell script to be executed by cron.  I have tried every possible permutation of:
cd /Users/friedman/hackjohn
conda activate hackjohn  **or** source /anaconda2/bin/activate hackjohn
/anaconda2/envs/hackjohn/bin/python hackjohn.py **or** python hackjohn.py **or**
hackjohn.py (with the proper shebang line at the top)

Could you share insight about how you got cron to properly activate the anaconda environment and use the proper version of python? thanks so much:)

**Comment by dhimmel** [comment]
Hey @ndfriedman thanks for your interest and sorry to hear about your cron environment issues.

What worked for me was to include a shebang as the first line of `hackjohn.py` like:

```
#!/home/dhimmel/anaconda3/envs/hackjohn/bin/python
```

This shebang should point to the python binary installed in the conda environment. Can you check that if you run the path to the python binary in a terminal that it opens python?

For example, when I run `/home/dhimmel/anaconda3/envs/hackjohn/bin/python` in my terminal, a Python session launches like:

```
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
