### ISSUE TITLE
IS this still working?

### ISSUE THREAD

**Issue by sudarshan2906** [dhimmel/hackjohn#5]
I am getting lots of error. I solved some of them but their is no Trailhead column in the df.

**Comment by dhimmel** [comment]
Looks like the trailhead names might have changed at https://www.nps.gov/yose/planyourvisit/fulltrailheads.htm

![image](https://user-images.githubusercontent.com/1117703/82752805-a6592b80-9d8e-11ea-812d-b59ac7c9b4df.png)

I will look into it. Can you also list the other problems you solved, so we don't duplicate efforts?

**Comment by dhimmel** [comment]
Fixed in https://github.com/dhimmel/hackjohn/commit/3a01193752baf4342cba871887f4de155f6cc714. The main change that was needed was to skip the first row of the HTML table which was added at some point:

```html
<tr height="25" style="height:18.75pt">
    <td class="xl73" colspan="6" height="25"
        style="border:none; height:18.75pt; width:499pt; text-align:left; padding-top:1px; padding-right:1px; padding-left:1px; vertical-align:bottom; white-space:nowrap"
        width="666"><span style="font-size:11pt"><span style="color:black"><span style="font-weight:400"><span
                        style="font-style:normal"><span style="text-decoration:none"><span
                                style="font-family:Calibri,sans-serif">Report Date:<br>
                                05/23/2020 10:46 AM</span></span></span></span></span></span></td>
</tr>
```

Another change is that the table:

> If a date does not appear in the chart below, there is no space on the Donohue Exit Quota for that day.

However, this doesn't actually affect hackjohn.

**Comment by dhimmel** [comment]
I also added GitHub Actions and scheduled weekly runs. This way I should get notified if the code breaks in the future.

It'd be possible to set it up so GitHub actions could notify you as well. If someone wants to contribute this feature, that'd be cool. Personally, I've already done the JMT!
